name: landmark
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.12.9
  - numpy>=1.23.0
  - pandas>=2.0.0
  - scipy>=1.10.0
  - seaborn>=0.12.0
  - plotly>=5.15.0
  - scikit-learn>=1.2.0
  - tensorflow>=2.18.0
  - matplotlib>=3.7.0
  - jupyter>=1.0.0
  - xgboost>=1.7.0
  - lightgbm>=3.3.0
  - ipython
  - ipykernel
  - python-kaleido>=0.2.1
  - pytorch==2.5.1
  - xlrd==2.0.1
  - graphviz==13.1.0
  - scikit-optimize==0.10.2
  - pillow==11.3.0
  - torchvision==0.20.1
